{% set name = "spinsfast" %}
{% set version = "104.2020.8.20.0.32.20" %}
{% set sha256 = "f211409f122be88363b0466beb783959fafe4a30c6b31060856479c714f69860" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4

requirements:
  build:
    - {{ compiler('c') }}                # [not win]
    - {{ compiler('m2w64_c') }}          # [win]
  host:
    - python ==2.7
    - pip
    - numpy
    - fftw
  run:
    - python ==2.7
    - {{ pin_compatible('numpy') }}
    - fftw

test:
  imports:
    - spinsfast

about:
  home: https://github.com/moble/spinsfast
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Fast and exact spin-s spherical-harmonic transforms
  dev_url: https://github.com/moble/spinsfast

extra:
  recipe-maintainers:
    - moble
