{% set name = "spinsfast" %}
{% set version = "104.2020.8.18.23.32.32" %}
{% set sha256 = "447d6a0494fa6156a88f57e142d4be260517240fda2401af2638b5686d04b058" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: package_version={{ version }} {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv  # [not win]
  #script: set "package_version={{ version }}" && {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv  # [win]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - fftw
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - fftw

test:
  imports:
    - spinsfast

about:
  home: https://github.com/moble/spinsfast
  license: GPL3
  license_family: GPL
  license_file: LICENSE
  summary: Fast and exact spin-s spherical-harmonic transforms
  dev_url: https://github.com/moble/spinsfast

extra:
  recipe-maintainers:
    - moble
