{% set name = "spinsfast" %}
{% set version = "2022.4.3" %}
{% set sha256 = "1bb2bd7a36c655b6704be474a8b03daccb03319ccbdcb89f3be0e70fbced707b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win or py<38]
  number: 1
  script: /bin/rm -f pyproject.toml && {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv  # [not win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - fftw
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - fftw

test:
  imports:
    - spinsfast

about:
  home: https://github.com/moble/spinsfast
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Fast and exact spin-s spherical-harmonic transforms
  dev_url: https://github.com/moble/spinsfast

extra:
  recipe-maintainers:
    - moble
