{% set name = "spinsfast" %}
{% set version = "104.2022.2.8.21.41.41" %}
{% set sha256 = "085a6337730e79cb4a1a74e239d870597f11be7c955c2ee15aaf7af46616715d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: package_version={{ version }} {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv  # [not win]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - fftw
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - fftw

test:
  imports:
    - spinsfast

about:
  home: https://github.com/moble/spinsfast
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Fast and exact spin-s spherical-harmonic transforms
  dev_url: https://github.com/moble/spinsfast

extra:
  recipe-maintainers:
    - moble
